[package]
name = "bubshurb/promisecleanuputil"
description = "An utility module for working with [Promise](https://eryn.io/roblox-lua-promise/) cleanups."
authors = ["bubshurb"]
license = "MIT"
version = "1.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"