[package]
name = "bubshurb/playerpolicyinfoutil"
description = "A very simple utility module for retrieving a player's policy info safely."
authors = ["bubshurb"]
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"