[package]
name = "bubshurb/property"
description = "A class for wrapping values around setters and getters."
authors = ["bubshurb"]
version = "3.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Trove = "sleitnick/trove@1"
Promise = "evaera/promise@4"