[package]
name = "bub/playereventsutil"
description = "A simple utility module for working with player events."
authors = ["bub"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"